variables:
  IMAGE_TAG: "1.0"
  DOCKER_IMAGE: "registry.insidelabs-git.mathworks.com/cbollige/matlab-devops-registry/matlab-devops-r2024b"

stages:
  - test
  - deploy
  - publish

unit-test-job:
  stage: test
  tags:
    - docker-exec
  image: 
    name: $DOCKER_IMAGE:$IMAGE_TAG
  script:
    - echo "Running unit tests..."
    - matlab-batch "buildtool check test -verbosity Verbose"
  coverage: '/Statement: \d+/\d+ \((\d+\.\d+)%\)/'
  artifacts:
    when: always
    paths:
      - public
    reports:
      junit: public/test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: public/code-coverage/cobertura-coverage.xml

visdiff:
  stage: test
  tags:
    - docker-exec
  image: 
    name: $DOCKER_IMAGE:$IMAGE_TAG
  script:
    - echo "Comparing current version of MATLAB app to status in main branch..."
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - matlab-batch "buildtool publishAppDiffToMain('visdiff') -verbosity Verbose"
    - echo "Report published as artifact in visdiff folder"
  dependencies: [] # Prevent downloading of artifacts from previous jobs
  artifacts:
    paths:
      - visdiff/*
  except:
    - main

deploy-job:
  stage: deploy
  tags:
    - docker-exec
  image: 
    name: $DOCKER_IMAGE:$IMAGE_TAG
  script:
    - echo "Deploying ctf and web app..."
    - matlab-batch "disp('Run deployWebApp(archiveSuffix) tasks to deploy the MATLAB app to the Web App Server')"
    - matlab-batch "disp('Run deployMPSArchive(mpsArchiveName), deployFrontend, and integrationTest tasks')"
  artifacts:
    when: always
    paths:
      - public
  #only:
  #  - main

pages:
  stage: publish
  tags:
    - linux
  script:
    - echo "Creating Gitlab pages"
  artifacts:
    paths:
      - public
  #only:
  #  - main
