stages:
  - test
  - coverage
  - deploy
  - integration-test

unit-test-job:
  stage: test
  tags:
    - on-prem
  script:
    - echo "Running unit tests..."
    #- matlab-batch -licenseToken "cbollige@mathworks.com|cbolligeAll|$MLM_LICENSE_TOKEN" "ver;"
    - mw -using Bmain matlab -softwareopengl -batch "openProject(pwd); buildtool test;"
    - mw -using Bmain matlab -softwareopengl -batch "load(fullfile('code-coverage','coverage.mat')); disp(coverage);"
  artifacts:
    paths:
      - test-reports/
      - code-coverage/
    reports:
      junit: test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: code-coverage/cobertura-coverage.xml
  coverage: '/Statement: \d+/\d+ \((\d+\.\d+)%\)/'

deploy-job:
  stage: deploy
  tags:
    - on-prem
  script:
    - echo "Deploying ctf and web app..."
    - mw -using Bmain matlab -softwareopengl -batch "openProject(pwd); buildtool deployCtf deployWebApp;"

pages:
  stage: deploy
  tags:
    - linux
  script:
    - mkdir public
    - cp source/index.html public/
    - cp -r code-coverage/ public/
    - cp -r test-reports/ public/
  artifacts:
    paths:
      - public
  only:
    - main

test-endpoint:
  stage: integration-test
  tags:
    - docker
  image: curlimages/curl:latest
  script:
    - |
      # Make a request and capture the response
      RESPONSE=$(curl --silent --location 'https://ipws-mps.mathworks.com/shortestTrip/shortestTrip' --header 'Content-Type: application/json' --data ' {"rhs":[[1,1,2,2],[1,2,2,1]],"nargout":1,"outputFormat":{"mode":"small","nanType":"string"}}')

      # Define the expected response as a string
      EXPECTED_RESPONSE='{"lhs":[[[1,2,3,4]]]}'

      # Check if the actual response matches the expected response; string comparison is enough in our case
      if [ "$RESPONSE" = "$EXPECTED_RESPONSE" ]; then
        echo "Test passed: Received expected response"
      else
        echo "Test failed: Unexpected response"
        echo "Expected: $EXPECTED_RESPONSE"
        echo "Received: $RESPONSE"
        exit 1
      fi