variables:
  IMAGE_TAG: "1.0"
  DOCKER_IMAGE: "registry.insidelabs-git.mathworks.com/cbollige/matlab-devops-registry/matlab-devops-r2024b"

stages:
  - test
  - build
  - deploy
  - publish

unit-test-job:
  stage: test
  tags:
    - docker-exec
  image: 
    name: $DOCKER_IMAGE:$IMAGE_TAG
  script:
    - echo "Running unit tests..."
    - matlab-batch "buildtool check test -verbosity Verbose"
  coverage: '/Statement: \d+/\d+ \((\d+\.\d+)%\)/'
  artifacts:
    when: always
    paths:
      - public
    reports:
      junit: public/test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: public/code-coverage/cobertura-coverage.xml

visdiff:
  stage: test
  tags:
    - docker-exec
  image: 
    name: $DOCKER_IMAGE:$IMAGE_TAG
  script:
    - echo "Comparing current version of MATLAB app to status in main branch..."
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - matlab-batch "buildtool publishAppDiffToMain('visdiff') -verbosity Verbose"
    - echo "Report published as artifact in visdiff folder"
  dependencies: [] # Prevent downloading of artifacts from previous jobs
  artifacts:
    paths:
      - visdiff/*
  except:
    - main

build-job:
  stage: build
  tags:
    - docker-exec
  image: 
    name: $DOCKER_IMAGE:$IMAGE_TAG
  script:
    - echo "Building web app..."    
    - matlab-batch "buildtool buildWebApp('TEST',upper(getenv('GITLAB_USER_LOGIN'))) -verbosity Verbose"
    #- echo "Deploying production server archive and html frontend..."
    #- matlab-batch "mpsArchiveName=['shortestTrip',upper(getenv('GITLAB_USER_LOGIN'))]; disp(mpsArchiveName); buildtool deployMPSArchive(mpsArchiveName) deployFrontend integrationTest -verbosity Verbose"
  artifacts:
    when: always
    paths:
      - deploy

deploy-job:
  stage: deploy
  tags:
    - on-prem
  script:
    - echo "Deploying web app..."    
    - cp deploy/webapp/TravelingSalesman.ctf "/mathworks/inside/labs/matlab/mathworks/inside/labs/matlab/mwa/TravelingSalesman-TEST/TravelingSalesman_$GITLAB_USER_LOGIN.ctf"
  artifacts:
    when: always
    paths:
      - deploy

pages:
  stage: publish
  tags:
    - linux
  script:
    - echo "Creating Gitlab pages"
  artifacts:
    paths:
      - public