stages:
  - test
  - coverage
  - deploy

unit-test-job:
  stage: test
  tags:
    - on-prem
  script:
    - echo "Running unit tests..."
    - mw -using Bmain matlab -softwareopengl -batch "openProject(pwd); buildtool test;"
    - mw -using Bmain matlab -softwareopengl -batch "load(fullfile('code-coverage','coverage.mat')); disp(coverage);"
  artifacts:
    paths:
      - test-reports/
      - code-coverage/
    reports:
      junit: test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: code-coverage/cobertura-coverage.xml
  coverage: '/Statement: \d+/\d+ \((\d+\.\d+)%\)/'

deploy-job:
  stage: deploy
  tags:
    - on-prem
  script:
    - echo "Deploying ctf..."
    - mw -using Bmain matlab -softwareopengl -batch "openProject(pwd); buildtool deployCtf;"

pages:
  stage: deploy
  tags:
    - linux
  script:
    - mkdir public
    - cp source/index.html public/
    - cp -r code-coverage/ public/
    - cp -r test-reports/ public/
  artifacts:
    paths:
      - public
  only:
    - main