stages:
  - test
  - deploy
  - integration-test

unit-test-job:
  stage: test
  tags:
    - on-prem
  script:
    - echo "Running unit tests..."
    #- Invoke-WebRequest https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/win64/matlab-batch.exe -OutFile matlab-batch.exe
    #- ./matlab-batch -licenseToken "cbollige@mathworks.com|cbolligeAll|$MLM_LICENSE_TOKEN" "ver;"
    - mw -using BR2024bd matlab -softwareopengl -batch "buildtool check test;"
  artifacts:
    when: always
    paths:
      - test-reports/
      - code-coverage/
    reports:
      junit: test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: code-coverage/cobertura-coverage.xml

pages:
  stage: deploy
  tags:
    - on-prem
  script:
    - echo "Deploying test and coverage results..."
    - mw -using BR2024bd matlab -softwareopengl -batch "buildtool displayCoverage copyTestReports;"
    - echo "Deploying ctf and web app..."
    - mw -using BR2024bd matlab -softwareopengl -batch "mpsArchiveName=['shortestTrip',upper(getenv('GITLAB_USER_LOGIN'))]; disp(mpsArchiveName); mwaArchiveName=['TravelingSalesman',upper(getenv('GITLAB_USER_LOGIN'))]; disp(mwaArchiveName); buildtool deployFrontend(mpsArchiveName) deployMPSArchive(mpsArchiveName) deployWebApp(mwaArchiveName);"
  coverage: '/Statement: \d+/\d+ \((\d+\.\d+)%\)/'
  artifacts:
    paths:
      - public

visdiff:   
  stage: deploy
  tags:
    - on-prem
  script:
    - echo "Comparing current version of MATLAB app to status in main branch..."
    - mw -using BR2024bd matlab -softwareopengl -batch "buildtool publishAppDiffToMain('visdiff');"
    - echo "Report published as artifact in visdiff folder"
  artifacts:
    paths:
      - visdiff/*
  except:
    - main

test-endpoint:
  stage: integration-test
  tags:
    - on-prem
  script:
    - echo "Run integration test..."
    - mw -using BR2024bd matlab -softwareopengl -batch "setenv('MPS_ARCHIVE_NAME',['shortestTrip',upper(getenv('GITLAB_USER_LOGIN'))]); disp(getenv('MPS_ARCHIVE_NAME')); buildtool integrationTest;"