variables:
  IMAGE_TAG: "1.0"
  DOCKER_IMAGE: "registry.insidelabs-git.mathworks.com/cbollige/matlab-devops-registry/matlab-devops-r2024b"

stages:
  - deploy
  - publish

matlab-build:
  stage: deploy
  tags:
    - docker-exec
  image: 
    name: $DOCKER_IMAGE:$IMAGE_TAG
  script:
    - echo "Running unit tests..."
    #- matlab-batch "buildtool check test -verbosity Verbose"
    - echo "Deploying web app..."   
    - matlab-batch "buildtool deployWebApp('TEST') -verbosity Verbose"
    - echo "Deploying production server archive and html frontend..."
    #- matlab-batch "mpsArchiveName=['shortestTrip',upper(getenv('GITLAB_USER_LOGIN'))]; disp(mpsArchiveName); buildtool deployMPSArchive(mpsArchiveName) deployFrontend integrationTest -verbosity Verbose"
  coverage: '/Statement: \d+/\d+ \((\d+\.\d+)%\)/'
  artifacts:
    when: always
    paths:
      - public
    reports:
      junit: public/test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: public/code-coverage/cobertura-coverage.xml

pages:
  stage: publish
  tags:
    - linux
  script:
    - echo "Creating Gitlab pages"
  artifacts:
    paths:
      - public