variables:
  MPS_ARCHIVE_NAME: "shortestPath"
  MWA_ARCHIVE_NAME: "TravelingSalesman"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        MPS_ARCHIVE_NAME: "shortestPath_${CI_PROJECT_NAME}_${GITLAB_USER_NAME// /_}"
        MWA_ARCHIVE_NAME: "TravelingSalesman_${CI_PROJECT_NAME}_${GITLAB_USER_NAME// /_}"
    - if: '$CI_COMMIT_BRANCH != "main"'
      variables:
        MPS_ARCHIVE_NAME: "shortestPath_${CI_PROJECT_NAME}_${GITLAB_USER_NAME// /_}_${CI_COMMIT_BRANCH}"
        MWA_ARCHIVE_NAME: "TravelingSalesman_${CI_PROJECT_NAME}_${GITLAB_USER_NAME// /_}_${CI_COMMIT_BRANCH}"

stages:
  - test
  - deploy
  - integration-test

unit-test-job:
  stage: test
  tags:
    - on-prem
  script:
    - echo "Running unit tests..."
    #- Invoke-WebRequest https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/win64/matlab-batch.exe -OutFile matlab-batch.exe
    #- ./matlab-batch -licenseToken "cbollige@mathworks.com|cbolligeAll|$MLM_LICENSE_TOKEN" "ver;"
    - mw -using Bmain matlab -softwareopengl -batch "buildtool test;"
  artifacts:
    paths:
      - test-reports/
      - code-coverage/
    reports:
      junit: test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: code-coverage/cobertura-coverage.xml

deploy-job:
  stage: deploy
  tags:
    - on-prem
  script:
    - echo "Deploying test and coverage results..."
    - mw -using Bmain matlab -softwareopengl -batch "buildtool displayCoverage copyTestReports;"
    - echo "Deploying ctf and web app..."
    - mw -using Bmain matlab -softwareopengl -batch "buildtool deployFrontend('$MPS_ARCHIVE_NAME') deployMPSArchive('$MPS_ARCHIVE_NAME') deployWebApp('$MWA_ARCHIVE_NAME');"
  coverage: '/Statement: \d+/\d+ \((\d+\.\d+)%\)/'
  #only:
  #  - main

test-endpoint:
  stage: integration-test
  tags:
    - on-prem
  script:
    - echo "Run integration test..."
    - mw -using Bmain matlab -softwareopengl -batch "buildtool integrationTest;"
  only:
    - main