stages:
  - test
  - coverage

unit-test-job:
  stage: test
  tags:
    - on-prem
  script:
    - echo "Running unit tests..."
    - mw -using Bmain matlab -softwareopengl -batch "openProject(pwd); buildtool test;"
  artifacts:
    paths:
      - code-coverage/
    reports:
      cobertura: code-coverage/cobertura-coverage.xml

coverage-job:
  stage: coverage
  script:
    - echo "Publishing coverage report..."
  artifacts:
    paths:
      - code-coverage/
    when: always
  only:
    - main