stages:          # List of stages for jobs, and their order of execution
  - test
  - deploy

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - on-prem
  script:
    - echo "Running unit tests..."
    - mw -using Bmain matlab -softwareopengl -batch "openProject(pwd); buildtool test;"
  artifacts:
    untracked: false
    when: on_success
    access: all
    paths:
      - ""code-coverage""
pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - "code-coverage"
  only:
    - main  # or the branch you want to deploy from