stages:
  - test
  - coverage
  - deploy
  - integration-test

unit-test-job:
  stage: test
  tags:
    - on-prem
  script:
    - echo "Running unit tests..."
    #- Invoke-WebRequest https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/win64/matlab-batch.exe -OutFile matlab-batch.exe
    #- ./matlab-batch -licenseToken "cbollige@mathworks.com|cbolligeAll|$MLM_LICENSE_TOKEN" "ver;"
    - mw -using Bmain matlab -softwareopengl -batch "buildtool test displayCoverage copyTestReports;"
  artifacts:
    paths:
      - test-reports/
      - code-coverage/
    reports:
      junit: test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: code-coverage/cobertura-coverage.xml
  coverage: '/Statement: \d+/\d+ \((\d+\.\d+)%\)/'

deploy-job:
  stage: deploy
  tags:
    - on-prem
  script:
    - echo "Deploying ctf and web app..."
    - mw -using Bmain matlab -softwareopengl -batch "buildtool deployFrontend deployMPSArchive deployWebApp;"
  only:
    - main

test-endpoint:
  stage: integration-test
  tags:
    - on-prem
  script:
    - echo "Run integration test..."
    - mw -using Bmain matlab -softwareopengl -batch "buildtool integrationTest;"
  only:
    - main