stages:
  - test
  - deploy
  - integration-test

unit-test-job:
  stage: test
  tags:
    - on-prem
  script:
    - echo "Running unit tests..."
    #- Invoke-WebRequest https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/win64/matlab-batch.exe -OutFile matlab-batch.exe
    #- ./matlab-batch -licenseToken "cbollige@mathworks.com|cbolligeAll|$MLM_LICENSE_TOKEN" "ver;"
    - mw -using Bmain matlab -softwareopengl -batch "buildtool test;"
  artifacts:
    paths:
      - test-reports/
      - code-coverage/
    reports:
      junit: test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: code-coverage/cobertura-coverage.xml

deploy-job:
  stage: deploy
  tags:
    - on-prem
  script:
    - echo "Deploying test and coverage results..."
    - mw -using Bmain matlab -softwareopengl -batch "buildtool displayCoverage copyTestReports;"
    - echo "Deploying ctf and web app..."
    - mw -using Bmain matlab -softwareopengl -batch "mpsArchiveName=\"shortestPath\"+upper(getenv(\"GITLAB_USER_LOGIN\")); disp(mpsArchiveName); mwaArchiveName=\"TravelingSalesman\"+upper(getenv(\"GITLAB_USER_LOGIN\"); disp(mwaArchiveName); buildtool deployFrontend(mpsArchiveName) deployMPSArchive(mpsArchiveName) deployWebApp(mwaArchiveName);"
  coverage: '/Statement: \d+/\d+ \((\d+\.\d+)%\)/'
  #only:
  #  - main

test-endpoint:
  stage: integration-test
  tags:
    - on-prem
  script:
    - echo "Run integration test..."
    - mw -using Bmain matlab -softwareopengl -batch "setenv(\"MPS_ARCHIVE_NAME\",\"shortestPath\"+upper(getenv(\"GITLAB_USER_LOGIN\"))); buildtool integrationTest;"
  only:
    - main