stages:
  - test
  - coverage

unit-test-job:
  stage: test
  tags:
    - on-prem
  script:
    - echo "Running unit tests..."
    - mw -using Bmain matlab -softwareopengl -batch "openProject(pwd); buildtool test;"
  artifacts:
    paths:
      - test-reports/
      - code-coverage/
    reports:
      junit: test-reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: code-coverage/cobertura-coverage.xml

coverage-job:
  stage: coverage
  tags:
    - on-prem
  script:
    - echo "Publishing coverage report..."
  artifacts:
    paths:
      - code-coverage/
    when: always
  only:
    - main