# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on: 
  push:                       # Runs on push events
  workflow_dispatch:          # Allows you to run this workflow manually from the Actions tab

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }}
  PRODUCT_LIST: MATLAB MATLAB_Test MATLAB_Compiler MATLAB_Compiler MATLAB_Compiler_SDK Optimization_Toolbox Global_Optimization_Toolbox Parallel_Computing_Toolbox MATLAB_Report_Generator

jobs:

  # This workflow contains two jobs called "test" and "compile-deployment"
  test:
    # This job will run for all the OS present in the matrix
    strategy:
      matrix:
         os: [ubuntu-latest]
        #os: [ubuntu-latest, windows-latest, macos-13]
     
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
 
    steps:
      - uses: actions/checkout@v4
       
      - name: Setup MATLAB on the GitHub Actions runner
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
          products: ${{ env.PRODUCT_LIST }}
            
      - name: Start display server (required for building doc in MATLAB)
        run: |
          Xvfb :99 & 
          echo "DISPLAY=:99" >> $GITHUB_ENV
 
      - name: Run Test
        uses: matlab-actions/run-build@v2
        with:
          tasks: test
          build-options: -parallel
          #use-parallel: true
          #test-results-junit: test-reports/junit.xml
          #code-coverage-cobertura: code-coverage\cobertura-coverage.xml

      - name: Junit Test Summary
        uses: test-summary/action@v2
        with:
           paths: "test-reports/junit.xml"

  compile-deployment:
    
    needs: test

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MATLAB on the GitHub Actions runner
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
          products: ${{ env.PRODUCT_LIST }}
      - name: Start display server (required for building doc in MATLAB)
        run: |
          Xvfb :99 & 
          echo "DISPLAY=:99" >> $GITHUB_ENV
 
      - name: Run Test
        uses: matlab-actions/run-build@v2
        with:
          tasks: deployMPSArchive
          tasks: deployWebApp
          
      - name: Upload Server Archive 
        uses: actions/upload-artifact@v4
        with:
          name: Travel Man WebApp and Production Server Archive 
          path: shortestTripproductionServerArchive   
          path: TravelingSalesmanwebAppArchive

#      - name: Publish Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        with:
#           files: "test-reports/junit.html"
 
 #     - name: Run un ${{ matrix.os }} with script
 #       uses: matlab-actions/run-command@v2
 #       with:
 #         command: myscript